### ISSUE TITLE
Error with CustomerChangePasswordCommand.php

### ISSUE THREAD

**Issue by EL-Nazer** [Vinai/module-customer-password-command#2]
Warning: Unsupported declare 'strict_types' in /vendor/vinaikopp/module-customer-password-command/Command/CustomerChangePasswordCommand.php on line 3

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /vendor/vinaikopp/module-customer-password-command/Command/CustomerChangePasswordCommand.php on line 86

**Comment by peterjaap** [comment]
You need at least PHP 7.0 to run Magento 2. You are probably running on PHP 5.6.
