### ISSUE TITLE
Php 7.2 compat

### ISSUE THREAD

**Issue by jg-development** [Vinai/module-customer-password-command#4]
Hi,
I am using/upgrading to Magento 2.3. The problem is, that the extension only works with 7.1
and magento/framework 1.101.
Could you update the extension for php 7.2?
Greetings Jan

**Comment by Vinai** [comment]
Hi Jan,

sure, I'll do that some time today.

**Comment by jg-development** [comment]
thx

**Comment by Vinai** [comment]
It should be okay now - can you do me a favor and let me know if you now are able to install it?

**Comment by jg-development** [comment]
yes it works ... thx
