### ISSUE TITLE
Magento 2.4 compatibility

### ISSUE THREAD

**Issue by Morgy93** [Vinai/module-customer-password-command#5]
The requirements don't cope with Magento version 2.4 anymore.

For example magento/product-community-edition 2.4.0 requires magento/framework 103.0.0

```
  "require": {
    "php": "^7.0.0|^7.1.0|^7.2.0",
    "magento/module-customer": "^100.1.1|^101.0|^102.0",
    "magento/framework": "^100.1.1|^101.0|^102.0",
    "symfony/console": "~2.3|~4.1"
  },
```

**Comment by Vinai** [comment]
Hi @Morgy93, please open a PR and I'm happy to merge it!

**Comment by DominicWatts** [comment]
This is resolved?

**Comment by Vinai** [comment]
Should be thanks to your PR
